### ISSUE TITLE
error paths for headers vs bodies

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/swagger2#57]
At the moment, the path starts at the object level "/", it may be beneficial to add a root to that to allow one to tell if a validation has failed in the header vs the body..

for example "header/x-header-name/" and "body/" perhaps..

Just getting this thought down, will have a think about it over xmas

**Comment by jhthorsen** [comment]
I disagree. All the top level names can be looked up by the "name" set in the specification. The "body" key is not because it's from the HTTP POST body, but because the body parameter has the name "body".

**Comment by mrenvoize** [comment]
I was really really unclear here.. oops.

I was talking about the error responses we output for a bad request.

So for a 500 for example, I had errors in header, but I had no simple way to see if the error was being thrown due to a bad header or a bad body...

**Comment by jhthorsen** [comment]
I know. That's exactly what I was talking about. Please provide an example.

**Comment by jhthorsen** [comment]
I'm closing this with hopefully a better explanation:

So you have something like this as input:

´´´
HTTP/1.1 200 OK\x0d
Content-Type: application/json;charset=UTF-8\x0d
x-bool: false\x0d
\x0d
{"what-ever":false}
´´´

If "what-ever" contains and invalid value, the error path will have "/body/what-ever", but the "body" prefix is set by what you use as "name" in the specification. Example spec with another prefix than "body": https://github.com/jhthorsen/swagger2/blob/master/t/bodytest.t#L99

On the other hand, "x-bool" in the header will not have any prefix. The error path will simply be "/x-bool".

**Comment by mrenvoize** [comment]
I see, I think what I missed was that it's only 'headers' that are missing the prefix. This makes much more sense to me now, thanks.

**Comment by jhthorsen** [comment]
Neither query params, path, nor headers have a "prefix". The thing is that the "name" key in for any given parameter (body, query param, placeholder, header, ...) all make up the first level in the JSON path. But since headers, query params, placeholders, ... only have one level there's nothing to prefix and you end up with a JSON path with just on part.

What we could do is that we could add an option to the plugin which prefix all the error paths, so you get something like this:

```
{
  "errors":[
    {"path":"/body/a","message":""},
    {"path":"/formData/a","message":""},
    {"path":"/path/x","message":""},
    {"path":"/query/y","message":""},
    {"path":"/header/z","message":""}
  ]
}
```

Pretty sure I will take a pull request for this feature - as long as it's not too much (or too complex) code.

**Comment by mrenvoize** [comment]
I think I'd certainly find it useful.. I'll take another look at the code some time as soon as the christmas rush at home has calmed down a bit.

**Comment by jhthorsen** [comment]
:+1:
