### ISSUE TITLE
Issues with x-mojo-around-action and Mojolicious around_action hook

### ISSUE THREAD

**Issue by knox1000** [jhthorsen/swagger2#77]
Looks like the around_action hooks are completing before the action runs for some reason.  I was under the impression that the around_action hooks should be able to run code after the action completes.

I've included some test files:

* test-mojo.pl - plain mojo around_action hook that appears to run in order.
* test-swagger2-hook-around-action.pl - swagger2 spec using the core mojo around_action hook, finishes before action is run/completes.
* test-swagger2-x-mojo-around-action.pl - swagger2 spec using the Swagger2 x-mojo-around-action, finishes before action is run/completes.

[hook-tests.zip](https://github.com/jhthorsen/swagger2/files/164308/hook-tests.zip)

**Comment by jhthorsen** [comment]
That's not the case here, since the "Swagger action" is always called async. Both work the same way though. If you want to run some code after the action is completed, I suggest you redefine the render_swagger() helper or define a render_swagger() method in your controller. The other way is to use http://mojolicious.org/perldoc/Mojolicious#before_render

**Comment by jhthorsen** [comment]
You might also want to join #swagger on irc.perl.org for asking questions like this.

**Comment by knox1000** [comment]
Excellent, thanks for the fast feedback!
